### ISSUE TITLE
map_builder.cpp 编译失败

### ISSUE THREAD

**Issue by Forrest-Z** [ningwang1028/ares_slam#1]
你好：
  我安装好g2o后编译时，在编译map_builder.cpp 时出错，错误代码在：
   SlamBlockSolver::LinearSolverType* linear_solver = new SlamLinearSolver;
    SlamBlockSolver* solver_ptr = new SlamBlockSolver(linear_solver); 
    g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(solver_ptr); // L-M

 你知道原因吗

**Comment by Forrest-Z** [comment]
你好，编译问题我解决了，主要是ros自带g2o与自装的冲突。但是，我又遇到了新问题，你这边的代码在订阅激光数据后，会一直卡在tf获取的代码那里，程序不会继续进行下去，你知道啥原因吗

**Comment by ningwang1028** [comment]
你好，运行建图时需要odom到base_link的tf数据

**Comment by lianshangni0922** [comment]
你好， 我在运行的过程中已经提供odom到base_link的tf数据，但是按照建图的TF，应该有map这个frame，在运行过程中tf_tree中没有这个map。想问一下这个该怎么解决，谢谢！
